import { describe, expect, it } from "vitest";
import { getDraftForKind, shouldAutoGenerateDraft } from "./content-drafts";

describe("content drafts", () => {
  it("returns the saved draft for the active kind immediately", () => {
    expect(getDraftForKind({ pitch: "p", blog: "b", post: "x" }, "blog")).toBe("b");
    expect(getDraftForKind({ pitch: "p" }, "post")).toBe("");
  });

  it("does not auto-generate when a draft already exists for that tab", () => {
    expect(
      shouldAutoGenerateDraft({
        owner: true,
        analyzed: true,
        activeKind: "blog",
        draft: "already here",
        contentLoading: false,
        alreadyTried: false,
      }),
    ).toBe(false);
  });

  it("auto-generates once for an empty blog or post tab", () => {
    expect(
      shouldAutoGenerateDraft({
        owner: true,
        analyzed: true,
        activeKind: "blog",
        draft: "",
        contentLoading: false,
        alreadyTried: false,
      }),
    ).toBe(true);
  });
});
