import type { ContentKind } from "@newshog/shared";

export function getDraftForKind(drafts: Record<string, string>, kind: ContentKind): string {
  return drafts[kind] ?? "";
}

export function shouldAutoGenerateDraft(opts: {
  owner: boolean;
  analyzed: boolean;
  activeKind: ContentKind;
  draft: string;
  contentLoading: boolean;
  alreadyTried: boolean;
}): boolean {
  return (
    opts.owner &&
    opts.analyzed &&
    opts.activeKind !== "pitch" &&
    !opts.draft &&
    !opts.contentLoading &&
    !opts.alreadyTried
  );
}
